import Link from "next/link";
import { ShieldCheck, Truck, Waves } from "lucide-react";
import { SiteHeader } from "@/components/site-header";
import { SiteFooter } from "@/components/site-footer";
import { ProductCard } from "@/components/product-card";
import { HeroBanner } from "@/components/hero-banner";
import { getCollections, getProducts } from "@/lib/catalog";
export const revalidate = 60;
export default async function Home() { const [products, collections] = await Promise.all([getProducts(), getCollections()]); return <main className="min-h-screen bg-white text-black"><SiteHeader/><HeroBanner/><section className="mx-auto grid max-w-7xl gap-4 px-5 py-12 md:grid-cols-3 lg:px-8">{[[Waves,"Chất âm được tuyển chọn","Cân bằng, rõ nét và phù hợp từng không gian."],[Truck,"Giao hàng toàn quốc","Đóng gói an toàn, theo dõi hành trình rõ ràng."],[ShieldCheck,"Bảo hành minh bạch","Thông tin chính sách được công bố trên từng sản phẩm."]].map(([Icon,title,copy])=><div key={String(title)} className="flex gap-4 rounded-2xl border border-black/8 bg-black/[.03] p-5"><Icon className="text-black"/><div><h2 className="font-semibold">{String(title)}</h2><p className="mt-1 text-sm leading-6 text-black/50">{String(copy)}</p></div></div>)}</section><section id="san-pham" className="mx-auto max-w-7xl px-5 py-14 lg:px-8"><div className="mb-8 flex items-end justify-between gap-5"><div><p className="text-sm uppercase tracking-[.2em] text-black">Nổi bật</p><h2 className="mt-2 text-3xl font-semibold tracking-tight sm:text-4xl">Âm thanh cho mọi nhịp sống</h2></div><Link href="/collections" className="hidden text-sm text-black/60 hover:text-black sm:block">Xem tất cả</Link></div><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{products.slice(0,6).map((product,index)=><ProductCard key={product.id} product={product} index={index}/>)}</div></section><section className="mx-auto max-w-7xl px-5 py-14 lg:px-8"><div className="grid gap-5 md:grid-cols-3">{collections.slice(0,3).map((collection,index)=><Link href="/collections" key={collection.id} className="min-h-52 rounded-[1.75rem] border border-black/10 bg-gradient-to-br from-black/[.08] to-transparent p-7 transition hover:-translate-y-1"><span className="text-sm text-black">0{index+1}</span><h3 className="mt-12 text-2xl font-semibold">{collection.name}</h3><p className="mt-2 text-sm leading-6 text-black/50">{collection.description}</p></Link>)}</div></section><SiteFooter/></main>; }
